version: "3.3"

services:
  frontend:
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        SISYPHUS_API_SERVER: ${SISYPHUS_API_SERVER}
    ports:
      - 3000:3000
