name: sisyphus-frontend

services:
  frontend:
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        SISYPHUS_API_SERVER: ${SISYPHUS_API_SERVER}
        SISYPHUS_DB_SERVER: ${SISYPHUS_DB_SERVER}
    ports:
      - 3000:3000
    networks:
      - sisyphus-frontend

networks:
  sisyphus-frontend: